base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.home, name="home"),
    path('login/', views.loginPage, name="login"),
    path('signup/', views.signupPage, name="signup"),
    path('logout/', views.logoutUser, name="logout"),
    path('dashboard/chunk_file/', views.chunk_file, name="chunk_file"),
    path('about/', views.about, name="about"),
    path('dashboard/splitted-files/', views.splitted_files, name='splitted_files'),
    path('documentation_intro/', views.documentation_intro, name="documentation_intro"),
    path('documentation_getting_started/', views.documentation_getting_started, name="documentation_getting_started"),
    path('documentation_how/', views.documentation_how, name="documentation_how"),
    path('documentation_dashboard/', views.documentation_dashboard, name="documentation_dashboard"),
    path('contact/', views.contact, name="contact"),
    path('dashboard/settings/', views.dashboard_setting, name="dashboard_settings"),
    path('faq/', views.faq, name="faq"),
    path('privacy/', views.privacy, name="privacy"),
    path('terms_condition/', views.t_c, name="t_c"),
    path('dashboard/', views.dashboard, name="dashboard")

]

go_chunk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.views.static import serve
from django.conf import settings
# from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("base.urls", namespace="base")),
    # url(r'^media/(?P<path>.*)$', serve,{'document_root':       settings.MEDIA_ROOT}), 
    # url(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}), 
]+  static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

base/models.py
# from datetime import timezone , datetime
# import datetime
import uuid
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()
from django.utils import timezone


class ChunkedFile(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    file_id = models.UUIDField(default=uuid.uuid4, primary_key=True)
    upload_time = models.DateTimeField(auto_now=True)
    saved = models.BooleanField(default=False)
    file = models.FileField(upload_to=f'files')

base/views.py
from datetime import datetime
from pickle import FALSE
from django.utils.datastructures import MultiValueDictKeyError
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout
from zipfile import  ZipFile, ZIP_DEFLATED
import pandas as pd
import os
# from datetime import datetime, timedelta
from .models import ChunkedFile
# Create your views here.


dir_path = os.path.dirname(os.path.realpath('go_chunk'))
folder_path = os.path.join(dir_path,'media')
converted_path = os.path.join(dir_path,'convert')
temp_folder_path = os.path.join(dir_path,'temp')
date = datetime.now().strftime("%M-%S")
print(folder_path)
def storingFile(saved, user, ouput_name, file, chunk_size,batch_no):
                if saved == 'on':
                    db_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    zip_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    for chunk in pd.read_csv(file, chunksize=chunk_size, encoding='Windows-1252'):
                        with ZipFile(zip_file_path, 'a') as zip_file:
                            file_name = f"{ouput_name}-" + str(batch_no) + ".csv"
                            zip_file.write(file_name,chunk.to_csv(file_name, index=False) ,compress_type=ZIP_DEFLATED)
                        os.remove(file_name)
                        batch_no += 1
                    csv_obj = ChunkedFile.objects.create(user=user, file=db_file_path)
                    csv_obj.save()

                if saved == False:
                    temp_zip_file_path = f'temp/{user}-{ouput_name}-{date}.zip'
                    temp_db_file_path = f'temp/{user}-{ouput_name}-{date}.zip'
                    for chunk in pd.read_csv(file, chunksize=chunk_size, encoding='Windows-1252'):
                        with ZipFile(temp_zip_file_path, 'a') as zip_file:
                            file_name = f"{ouput_name}-" + str(batch_no) + ".csv"
                            zip_file.write(file_name,chunk.to_csv(file_name, index=False) ,compress_type=ZIP_DEFLATED)
                        os.remove(file_name)
                        batch_no += 1
                    csv_obj = ChunkedFile.objects.create(user=user, file=temp_db_file_path)
                    csv_obj.save()
               
              
              
def storingJsonFile(saved, user, ouput_name, file, chunk_size,batch_no):
                if saved == 'on':
                    df = pd.read_json(file)
                    new_file = f'convert/{ouput_name}'
                    df.to_csv(new_file, index=0)
                    db_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    zip_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    for chunk in pd.read_csv(new_file, chunksize=chunk_size, encoding='Windows-1252'):
                        with ZipFile(zip_file_path, 'a') as zip_file:
                            file_name = f"{ouput_name}-" + str(batch_no) + ".json"
                            zip_file.write(file_name,chunk.to_json(file_name, index=True, orient='records') ,compress_type=ZIP_DEFLATED)
                        os.remove(file_name)
                        batch_no += 1
                    csv_obj = ChunkedFile.objects.create(user=user, file=db_file_path)
                    csv_obj.save()

                if saved == False:
                    df = pd.read_json(file)
                    new_file = f'convert/{ouput_name}'
                    df.to_csv(new_file, index=0)
                    db_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    zip_file_path = f'media/{user}-{ouput_name}-{date}.zip'
                    for chunk in pd.read_csv(new_file, chunksize=chunk_size, encoding='Windows-1252'):
                        with ZipFile(zip_file_path, 'a') as zip_file:
                            file_name = f"{ouput_name}-" + str(batch_no) + ".json"
                            zip_file.write(file_name,chunk.to_json(file_name, index=True, orient='records') ,compress_type=ZIP_DEFLATED)
                        os.remove(file_name)
                        batch_no += 1
                    csv_obj = ChunkedFile.objects.create(user=user, file=db_file_path)
                    csv_obj.save()


def home(request):
    return render(request, 'base/home.html')

def about(request):
    return render(request, 'base/about.html')

def documentation_intro(request):
    return render(request, 'base/documentation_intro.html')

def documentation_getting_started(request):
    return render(request, 'base/documentation_getting_started.html')

def documentation_how(request):
    return render(request, 'base/documentation_how.html')

def documentation_dashboard(request):
    return render(request, 'base/documentation_dashboard.html')



def contact(request):
    return render(request, 'base/contact.html')

def faq(request):
    return render(request, 'base/faq.html')

def privacy(request):
    return render(request, 'base/privacy.html')

def t_c(request):
    return render(request, 'base/t_c.html')


def loginPage(request):
    
    if request.user.is_authenticated:
        return redirect('/dashboard/')

    if request.method == "POST":
        username = request.POST.get('username').lower()
        password = request.POST.get('password')

        try:
            user = User.objects.get(username=username)
        except:
            messages.error(request, 'User does not exist')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/dashboard/')
        else:
            messages.error(request, 'Username or Password does not exist')

    return render(request, 'base/login.html')


def signupPage(request):
    if request.method == "POST":
        username = request.POST['username']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']
        if password != password2:
            messages.error(request, 'passwords do not match')
        #  return redirect('/signup')
        elif len(password) < 4:
            messages.error(request, 'password is too short')
        #  return redirect('/signup')
        elif User.objects.filter(username=username).exists():
            messages.error(request, 'username taken')
        #  return redirect('/signup')
        elif User.objects.filter(email=email).exists():
            messages.error(request, 'email already in use. if this is your account, please login')
        #  return redirect('/signup')
        else:
            new_user = User.objects.create_user(username=username, email=email, password=password)
            new_user.save()
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('/')       
    return render(request, 'base/signup.html')


def logoutUser(request):
    logout(request)
    messages.success(request, "Loggedout Successfully")
    return redirect('/')


@login_required(login_url='/login/')
def chunk_file(request):
    if request.method == "POST":
        file = request.FILES.get('doc')
        ouput_name = request.POST['file_name']
        chunk_size = request.POST['chunk_no']
        print(file)
        print(ouput_name)
        print(chunk_size)
        user = request.user
        if chunk_size == '' or file == None:
            messages.error(request, 'fields cannot be blank!')
            return redirect('/dashboard/chunk_file/')

        try:
            saved = request.POST['saved']
        except MultiValueDictKeyError:
            saved = False
            messages.error(request, "You didn't save the splited files. 15 minutes from now it will be deleted")
        if not os.path.exists(converted_path):
            os.mkdir(f'{dir_path}/convert')
        if not os.path.exists(folder_path):
            os.mkdir(f'{dir_path}/media')
        if not os.path.exists(temp_folder_path):
            os.mkdir(f'{dir_path}/temp')

        if  file.name.endswith('csv')  :
            if ouput_name == '':
                ouput_name = file.name
    
            chunk_size = int(chunk_size)
            batch_no = 1            
            # storing the chunked file in media folder or temp folder
            storingFile(saved, user, ouput_name,file, chunk_size,batch_no)
            messages.success(request, 'file has been split successfully')
            return redirect('/dashboard/chunk_file/')
            
        if  file.name.endswith('json')  :
            if ouput_name == '':
                ouput_name = file.name
    
            chunk_size = int(chunk_size)
            batch_no = 1
            
            # storing the chunked file in media folder or temp folder
            storingJsonFile(saved, user, ouput_name,file, chunk_size,batch_no)

            messages.success(request, 'file has been split successfully')
            return redirect('/dashboard/chunk_file/')


        else:
            messages.error(request, 'invalid file format')
    return render(request, 'base/chunk_file.html')
    
@login_required(login_url='/login/')   
def dashboard(request):
    return render(request, 'base/chunk_file.html')
    
@login_required(login_url='/login/')   
def dashboard_setting(request):
    return render(request, 'base/dashboard_settings.html')

@login_required(login_url='/login/')
def splitted_files(request):
    user=request.user 
    files = ChunkedFile.objects.all()

    if files.exists():
        files = ChunkedFile.objects.filter(user=user)
        return render(request, 'base/splitted_files.html', {'files':files})
        
    messages.error(request, 'file not found')

base/templates/authencation_main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Chunk File Project</title>

    <!-- Global Stylesheets -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/globalstyle.css' %}">

    <!-- Pages Stylesheets -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/signup.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/login.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/forgotpassword.css' %}">


</head>

<body>
    <main>


        {% if messages %}
        <ul class="messages absolute">
            {% for message in messages %}
            <div class=" p-0">
                <div class="alert show {{ message.tags }} alert-dismissible" role="alert">
                    <button class="close">
                        <span aria-hidden="True">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}

        {% endblock content %}



    </main>


    <script src="{% static 'js/faq.js' %}"></script>
    <script src="{% static 'js/footer.js' %}"></script>
    <script src="{% static 'js/header.js' %}"></script>
    <script>

        let alerts = document.querySelectorAll('.alert')
        let closes = document.querySelectorAll('.close')
        closes.forEach(closed => {
            closed.addEventListener('click', function () {
                alerts.forEach(alerted => {
                    alerted.classList.replace('show', 'hide')
                })
            })
        });

    </script>
</body>
<style>
    .alert {
        color: white;
        max-width: 400px;
        margin: auto;
        padding: 1rem 1rem;
        border-radius: .84rem;
        margin-top: .8rem;
    }

    .absolute {
        position: absolute;
        left: 50%;
        transform: translate(-50%);
        z-index: 999;
        top: 0;
    }

    .alert-danger {
        background-color: rgb(230, 105, 105);
    }

    .alert-success {
        background-color: rgb(112, 231, 108);
    }

    .show {
        animation: show_slide 1s ease forwards;
    }

    @keyframes show_slide {
        0% {
            transform: translateX(100%);
        }

        40% {
            transform: translateX(-10%);
        }

        80% {
            transform: translateX(0%);
        }

        100% {
            transform: translateX(-10px);
        }
    }

    .hide {
        animation: hide_slide 1s ease forwards;
    }

    @keyframes hide_slide {
        0% {
            transform: translateY(-10px);
        }

        40% {
            transform: translateY(0%);
        }

        80% {
            transform: translateX(-10%);
        }

        100% {
            transform: translateX(1000%);
        }
    }
</style>

</html>

base/templates/dashboard_main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>My Dashboard</title>

    <!-- Global Stylesheets -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/globalstyle.css' %}">

    <link rel="stylesheet" href="{% static 'styles/dashboard.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/dashboard-split.css' %}" />
    <link rel="stylesheet" href="{% static 'styles/dashboard-saved-files.css' %}">
    <link rel="stylesheet" href="{% static 'styles/dashboard-settings.css' %}">
    <script src="https://kit.fontawesome.com/0fb08dbc74.js" crossorigin="anonymous"></script>
</head>

<body>

    <main class="dashboard--container">
        {% include 'dashboard_nav.html' %}

        {% if messages %}
        <ul class="messages absolute">
            {% for message in messages %}
            <div class="container-fluid p-0">
                <div class="alert show {{ message.tags }} alert-dismissible" role="alert">
                    <button class="close">
                        <span aria-hidden="True">&times;</span>
                    </button>
                    {{ message }}
                </div>
            </div>
            {% endfor %}
        </ul>
        {% endif %}

        {% block content %}

        {% endblock content %}


    </main>



    <script>

        let alerts = document.querySelectorAll('.alert')
        let closes = document.querySelectorAll('.close')
        closes.forEach(closed => {
            closed.addEventListener('click', function () {
                alerts.forEach(alerted => {
                    alerted.classList.replace('show', 'hide')
                })
            })
        });

    </script>
    <script src=" {% static 'js/dashboard.js' %}"></script>
</body>
<style>
    .alert {
        color: white;
        min-width: 300px;
        max-width: 400px;
        margin: auto;
        padding: 1rem 1rem;
        border-radius: .84rem;
        margin-top: .8rem;
    }

    .absolute {
        position: absolute;
        left: 50%;
        transform: translate(-50%, 50%);
        z-index: 999;
    }

    .alert-danger {
        background-color: rgb(230, 105, 105);
    }

    .alert-success {
        background-color: rgb(112, 231, 108);
    }

    .show {
        animation: show_slide 1s ease forwards;
    }

    @keyframes show_slide {
        0% {
            transform: translateX(100%);
        }

        40% {
            transform: translateX(-10%);
        }

        80% {
            transform: translateX(0%);
        }

        100% {
            transform: translateX(-10px);
        }
    }

    .hide {
        animation: hide_slide 1s ease forwards;
    }

    @keyframes hide_slide {
        0% {
            transform: translateY(-10px);
        }

        40% {
            transform: translateY(0%);
        }

        80% {
            transform: translateX(-10%);
        }

        100% {
            transform: translateX(100%);
        }
    }
</style>

</html>

base/templates/dashboard_nav.html
{% load static %}
<!-- Navigation and Sidebar -->
<!-- Navigation -->
<div class="dashboard--nav">
    <div class="dashboard--nav--toggle">
        <div class="dashboard--nav--toggle__hover">
            <img src="{% static 'images/menu.png' %}" alt="toggle icon" class="dashboard--nav--toggle--icon" />
        </div>
        <a href="{% url 'base:home' %}"><img src="{% static 'images/LogoFooter.png' %}" alt="go-chunk-logo"
                class="dashboard--nav--toggle--logo" /></a>
    </div>
    <div class="dashboard--nav--user">
        <!-- <a href="">
            <img src="../images/icons for nav bar.png" alt="notification bell"
              class="dashboard--nav--user--bell">
          </a> -->
        <a href="../templates/dashboard-settings.html"><img src="{% static 'images/Group 199.png' %}" alt="user img"
                class="dashboard--nav--user--img"></a>
        <div class="dashboard--nav--online--icon"></div>
    </div>
</div>
<!-- SideBar -->
<div class="dashboard--sidebar">
    <div class="dashboard--sidebar--underline"></div>
    <div class="dashboard--sidebar--links__center">
        <!-- Sidebar link -->
        <a id="split-file-btn" href="{% url 'base:chunk_file' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/layer-group.svg' %}" alt="sidebar--icon"
                class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">Split File</p>
        </a>
        <!-- End of sidebar link -->
        <!-- Sidebar link -->
        <a href="{% url 'base:splitted_files' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/tick-square.png ' %}" alt="sidebar--icon"
                class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">Chunked Files</p>
        </a>
        <!-- End of sidebar link -->
        <!-- Sidebar link -->
        <a href="{% url 'base:faq' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/message-question.png  ' %}" alt="sidebar--icon"
                class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">FAQ</p>
        </a>
        <!-- End of sidebar link -->
        <!-- Sidebar link -->
        <a href="{% url 'base:dashboard_settings' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/setting-2.png  ' %}" alt="sidebar--icon"
                class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">Settings</p>
        </a>
        <!-- End of sidebar link -->
        <!-- Sidebar link -->
        <a href="{% url 'base:about' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/warning-2.png' %}" alt="sidebar--icon" class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">About Us</p>
        </a>
        <!-- End of sidebar link -->
        <!-- Sidebar link -->
        <a href="{% url 'base:logout' %}" class="dashboard--sidebar--links">
            <img src="{% static 'images/login.png ' %}" alt="sidebar--icon" class="dashboard--sidebar--links--icon">
            <p class="dashboard--sidebar--links--desc">Log Out</p>
        </a>
        <!-- End of sidebar link -->
    </div>
</div>
<!-- End of navigation and sidebar -->

base/templates/documentation_main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Documentation</title>

    <!-- Global Stylesheets -->
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/globalstyle.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/header.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/footer.css' %}">
    <link rel="stylesheet" type="text/css" media="screen" href="{% static 'styles/documentation.css' %}">

    <!-- Pages Stylesheets -->
    <script src="https://kit.fontawesome.com/0fb08dbc74.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


<body>
    <main>
        <!-- Navigation -->
        <div class="nav" id="myNav">
            <!-- Logo -->
            <div class="mobile-nav">
                <div class="menu-logo"> <a href="javascript:void(0);" class="icon" id="menu-icon">
                        <i class="fa fa-bars"></i>
                    </a>
                    <a href="{% url 'base:home' %}"><img src="{% static 'images/Frame 1028.png' %}" alt="" class="logo">
                </div>

                <img src="{% static 'images/search-interface-symbol.png' %}" alt="search" class="search">
            </div></a>
            <div class="logo-desktop"><a href="{% url 'base:home' %}"><img src="{% static 'images/Frame 1028.png' %}"
                        alt="" class="logo"></a>
            </div>

            <div class="documentation--middle--content">
                <img src="{% static 'images/Vector.svg' %}" alt="Github" class="github-icon">
                <!-- Search bar-->
                <div class="search-bar">
                    <img src="{% static 'images/search-interface-symbol.png' %}" alt="search">
                    <input type="search" name="" id="" class="search-input" placeholder="Search documentation">

                </div>
            </div>
            <!-- End of NavLinks -->
            <!-- Nav Buttons -->
            <div class="doc">
                {% if request.user.is_authenticated %}
                <span>Hello {{user.username}} | </span><a href="{% url 'base:logout' %}">Logout</a>
                {% else %}
                <a href="{% url 'base:login' %}"><button class="login-btn">Log in</button></a>
                <a href="{% url 'base:signup' %}"><button class="register-btn">Register</button></a>
                {% endif %}
            </div>
            <!-- End of Nav Buttons -->

        </div>
        <!-- ------End of navigation---------- -->
        <div class="main-container">
            <!-- Side nav -->
            <div class="side-nav">
                <h1 class="big-black-header">Documentation</h1>
                <ul>
                    <div class="intro-dropdown">
                        <li><a href="{% url 'base:documentation_intro' %}">Introduction</a></li><img
                            src="{% static 'images/down.png' %}" alt="" class="drop-down" id="dropdown-icon-1">
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu-1">
                        <h3><a href="{% url 'base:documentation_intro' %}#features">Features</a></h3>
                        <h3><a href="{% url 'base:documentation_intro' %}#getting_started">Getting
                                Started</a></h3>
                    </div>

                    <div class="intro-dropdown">
                        <li><a href="{% url 'base:documentation_getting_started' %}">Getting Started</a></li><img
                            src="{% static 'images/down.png' %}" alt="" class="drop-down" id="dropdown-icon-2">
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu-2">
                        <h3><a href="{% url 'base:documentation_getting_started' %}#signin">Sign in to the dashboard</a></h3>
                        <h3><a href="{% url 'base:documentation_getting_started' %}#chunk_your_file">Chunk
                                your CSV/JSON files</a></h3>
                        <h3><a href="{% url 'base:documentation_getting_started' %}#file_format">File Formats</a></h3>
                        <h3><a href="{% url 'base:documentation_getting_started' %}#manage_account">Manage your user account</a></h3>
                    </div>
                    <div class="intro-dropdown">
                        <li><a href="{% url 'base:documentation_dashboard' %}">Dashboard</a></li><img
                            src="{% static 'images/down.png' %}" alt="" class="drop-down" id="dropdown-icon-3">
                    </div>
                    <div class="dropdown-menu" id="dropdown-menu-3">
                        <h3><a href="{% url 'base:documentation_dashboard' %}#uploading">Uploading file</a></h3>
                        <h3><a href="{% url 'base:documentation_dashboard' %}#chunking">Chunking
                                Options</a></h3>
                        <h3><a href="{% url 'base:documentation_dashboard' %}#saving">Saving your file</a></h3>
                        <h3><a href="{% url 'base:documentation_dashboard' %}#frontend">font-end</a></h3>
                    </div>
                    <li><a href="#">Advanced
                            Installations</a></li>
                    <li><a href="{% url 'base:splitted_files' %}">Database </a></li>
                    <li><a href="{% url 'base:faq' %}">Frequently Asked Questions</a></li>
                    <li><a href="{% url 'base:contact' %}">Contact Us</a></li>
                    <li><a href="{% url 'base:home' %}">Website</a></li>
                    <li><a href="{% url 'base:privacy' %}">Privacy Policy</a></li>
                    <li><a href="{% url 'base:t_c' %}">Terms of Use</a></li>
                </ul>


            </div>
            <!-- End sinde nav -->
            {% block content %}

            {% endblock content %}


        </div>

        <script src="{% static 'js/documentation.js' %}"></script>
</body>

base/templates/navbar.html
{% load static %}
<nav>
  <div class="nav--logo--toggle">
    <img class="logo" src="{% static 'images/Frame 1028.png' %}" alt="" />
    <button type="submit">
      <img src="{% static 'images/bars.svg' %}" alt="" class="nav--toggle-btn">
    </button>
  </div>
  <div class="nav-links">
    <ul>
      <li><a href="{% url 'base:home' %}">Home</a></li>
      <li><a href="{% url 'base:documentation_intro' %}">Documentation</a></li>
      <li><a href="{% url 'base:contact' %}">Contact</a></li>
      <li><a href="{% url 'base:about' %}">About Us</a></li>
      <li><a href="{% url 'base:faq' %}">FAQs</a></li>
    </ul>
    <div class="nav--buttons">
      {% if request.user.is_authenticated %}
      <span>Hello {{user.username}} | </span><a href="{% url 'base:logout' %}">Logout</a>
      {% else %}
      <a href="{% url 'base:login' %}"><button class="login-btn">Log in</button></a>
      <a href="{% url 'base:signup' %}"><button class="register-btn">Register</button></a>
      {% endif %}
    </div>
  </div>
</nav>